# SPDX-License-Identifier: Apache-2.0

PROJECT_NAME := oxygen_gr-iio
REVISION := rev3
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS :=
M_DEPS :=

include ../../../common/oxygen/$(REVISION)/scripts/oxygen.mk
include ../../scripts/griio_proj.mk
