PROJECT_NAME := oxygen_default
REVISION := rev3
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS :=
M_DEPS :=

include ../../../common/oxygen/$(REVISION)/scripts/oxygen.mk
include ../../scripts/default_proj.mk
